Repository UBCSailbot/local-pathfinding, pull requests merged in 2022-08, with the labels that each got.

#291 Avoid ZeroDivisionError when global waypoints are the same
  python/handleInvalidState.py
Labels: bug

#292 Fix std_msg subscribers
  python/wandb_log_stats.py
Labels: bug

#293 Fix Wandb publishing rate
  python/wandb_log_latlon_plots.py
  python/wandb_log_stats.py
Labels: bug

#294 Only use AIS GPS for coordinates
  python/ros_interface.py
Labels: bug

#295 Correct typo in wandb node filename
  launch/main_loop_and_interface.launch
Labels: bug

#298 Update angle bounding and conventions
  python/MOCK_sensors.py
  python/ros_interface.py
  python/utilities.py
  test/test_utilities.py
Labels: bug, enhancement

#299 handled invalid AIS coordinates
  python/Sailbot.py
Labels: bug

#300 Increment global path index to first unreached waypoint on new path
  python/main_loop.py
Labels: enhancement

#303 Rebase #300
  python/main_loop.py
Labels: enhancement

#304 Ignore AIS ships by ID
  python/Sailbot.py
Labels: enhancement

#306 Add the olympic peninsula land mass files
  land_masses/olympic_peninsula_50.0m_08_28_2022-13_48_40.csv
  land_masses/olympic_peninsula_50.0m_08_28_2022-13_48_40.kml
Labels: enhancement

#307 Add vancouver island land mass and support multiple land masses
  land_masses/land_mass_creator.py
  land_masses/olympic_peninsula_depth_50m.csv
  land_masses/olympic_peninsula_depth_50m.kml
  land_masses/vancouver_island_depth_50m.csv
  land_masses/vancouver_island_depth_50m.kml
  launch/all.launch
  launch/main_loop_and_interface.launch
  launch/path_evaluator.launch
  python/obstacles.py
Labels: enhancement
